services:
  crackflix-scraper:
    image: ghcr.io/evilsloth/crackflix-scraper:master
    container_name: crackflix-scraper
    restart: always
    ports:
      - "3000:3000"
    environment:
      A4K_SCRAPER_BASE_URL: http://a4kscrapers-server:8091
      JACKETT_BASE_URL: http://jackett:9117
      JACKETT_API_KEY: "${CRACKFLIX_JACKETT_API_KEY}"
      ALL_DEBRID_AGENT: "${CRACKFLIX_ALL_DEBRID_AGENT}"
      ALL_DEBRID_API_KEY: "${CRACKFLIX_ALL_DEBRID_API_KEY}"
  a4kscrapers-server:
    image: ghcr.io/evilsloth/a4kscrapers-server:master
    container_name: a4kscrapers-server
    restart: always
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - AUTO_UPDATE=true
    volumes:
      - ~/compose-data/jackett/config:/config
      - ~/compose-data/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: always
